ports:
  - port: 3000
    onOpen: open-preview

tasks:
  - name: Auto Install & Start Draco
    init: npm install express
    command: |
      sudo su -c 'bash <(curl -s https://raw.githubusercontent.com/JishnuTheGamer/Vps/refs/heads/main/jishnu)'
      node keepalive.js
